In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [14]:
print(digits.keys())
print(digits['target'])
print(digits['images'])

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])
[0 1 2 ... 8 9 8]
[[[ 0.  0.  5. ...  1.  0.  0.]
  [ 0.  0. 13. ... 15.  5.  0.]
  [ 0.  3. 15. ... 11.  8.  0.]
  ...
  [ 0.  4. 11. ... 12.  7.  0.]
  [ 0.  2. 14. ... 12.  0.  0.]
  [ 0.  0.  6. ...  0.  0.  0.]]

 [[ 0.  0.  0. ...  5.  0.  0.]
  [ 0.  0.  0. ...  9.  0.  0.]
  [ 0.  0.  3. ...  6.  0.  0.]
  ...
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  1. ...  6.  0.  0.]
  [ 0.  0.  0. ... 10.  0.  0.]]

 [[ 0.  0.  0. ... 12.  0.  0.]
  [ 0.  0.  3. ... 14.  0.  0.]
  [ 0.  0.  8. ... 16.  0.  0.]
  ...
  [ 0.  9. 16. ...  0.  0.  0.]
  [ 0.  3. 13. ... 11.  5.  0.]
  [ 0.  0.  0. ... 16.  9.  0.]]

 ...

 [[ 0.  0.  1. ...  1.  0.  0.]
  [ 0.  0. 13. ...  2.  1.  0.]
  [ 0.  0. 16. ... 16.  5.  0.]
  ...
  [ 0.  0. 16. ... 15.  0.  0.]
  [ 0.  0. 15. ... 16.  0.  0.]
  [ 0.  0.  2. ...  6.  0.  0.]]

 [[ 0.  0.  2. ...  0.  0.  0.]
  [ 0.  0. 14. ... 15.  1.  0.]
  [ 0.  4. 16. ... 16.  7.  0.]
  ...
  [ 0.  0

In [17]:
n_samples = len(digits.images) #how many images we have
data1D = digits.images.reshape((n_samples, -1)) #turns data from 2d pixels to 1d
print(data1D)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [19]:
#train and test split

from sklearn.model_selection import train_test_split

train_image, test_image, train_target, test_target = \
    train_test_split(data1D, digits['target'])

In [48]:
#classifier
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(40, 40)) #making the mlp
mlp.fit(train_image, train_target)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(40, 40), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [49]:
predictions = mlp.predict(test_image) #generates predictions

from sklearn.metrics import confusion_matrix, classification_report

print(classification_report(test_target, predictions))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98        49
           1       0.93      0.97      0.95        38
           2       0.96      0.98      0.97        49
           3       1.00      0.94      0.97        52
           4       1.00      0.96      0.98        46
           5       0.88      0.91      0.89        55
           6       0.96      0.94      0.95        47
           7       0.93      1.00      0.96        37
           8       0.95      0.93      0.94        41
           9       0.89      0.92      0.90        36

   micro avg       0.95      0.95      0.95       450
   macro avg       0.95      0.95      0.95       450
weighted avg       0.95      0.95      0.95       450



In [41]:
print(confusion_matrix(test_target, predictions))

[[40  0  0  0  9  0  0  0  0  0]
 [ 0 33  1  0  0  0  1  1  2  0]
 [ 0  2 47  0  0  0  0  0  0  0]
 [ 0  3  2 30  0  0  0  7  8  2]
 [ 3  0  0  0 41  0  0  0  2  0]
 [ 3  0  0  1  1  1  0 42  4  3]
 [ 1  5  0  0  3  0 37  0  1  0]
 [ 2  0  1 14  0  0  1 18  1  0]
 [ 0 12  2  2  0  0  0  4 20  1]
 [ 1  0  0 11  0  1  0 19  3  1]]
